---
title: "CGM QC Features"
author: "Tyler Tong"
date: today
format:
  html:
    theme: cosmo
    embed-resources: true
    number-sections: true
    toc: true
    toc-depth: 4
    toc-location: left
    code-fold: false
engine: knitr
---

# Load packages

```{R}
#| message: false
#| warning: false
library(tidyverse)
library(readr)
library(gt)
library(purrr)
library(janitor)
library(jsonlite)
library(lubridate)
library(data.table)
library(iglu)
```

# Lead data

```{R}
#| message: false
#| warning: false
datapath <- "/Users/tt/Library/CloudStorage/Box-Box/ai-readi/v3-mini/dataset"
cgm_manifest_path <- "/wearable_blood_glucose/manifest.tsv"
participant_id <- c(1029, 1042)
manifest <- read_tsv(paste0(datapath, cgm_manifest_path))
cgm <- manifest |> 
  filter(person_id %in% participant_id) |>
  select(person_id, glucose_filepath) |> 
  mutate(
    full_path = paste0(datapath, glucose_filepath),
    json_data = map(full_path, ~ fromJSON(.x, flatten = TRUE))
  ) |> 
  unnest_wider(json_data) |> 
  mutate(header = map(header, ~ as.list(unlist(.x)))) |> 
  unnest_wider(header) |> 
  mutate(
    body = map(body, ~ {
      df <- .x[[1]] 
      as_tibble(df) |> mutate(across(everything(), as.character))
    })
  ) |> 
  unnest(cols = body) |> 
  type_convert() |> 
  select(-glucose_filepath, -full_path)
```

# Remove unneeded header variables

```{r}
#| message: false
#| warning: false
#| paged-print: true
cgm <- cgm |>
  select(!all_of(c(
     "person_id", 
     "creation_date_time", 
     "patient_id", 
     "schema_id.namespace", 
     "schema_id.version", 
     "modality", 
     "acquistion_rate.number_of_times", 
     "acquistion_rate.time_window.unit",
     "acquistion_rate.time_window.value", 
     "external_datasheets.datasheet_type", 
     "external_datasheets.datasheet_reference")))
```

# Clean cgm readings

```{R}
#| message: false
#| warning: false
cgm <- cgm |>
  filter(event_type == "EGV")
cgm <- cgm |>
  select(!all_of(c(
     "source_device_id", 
     "transmitter_id", 
     "effective_time_frame.time_interval.end_date_time", 
     "transmitter_time.unit", 
     "transmitter_time.value")))
cgm <- cgm |>
  mutate(cgm_raw = blood_glucose.value) |>
  mutate(blood_glucose.value = 
           case_when(
             grepl(
               "^[0-9]+$", blood_glucose.value) ~ 
               as.integer(blood_glucose.value), 
                     .default = NA))
```

# Get location based on timezone

```{r}
#| message: false
#| warning: false
cgm <- cgm |>
  mutate(location = case_when(
         (cgm$timezone == "pst" | cgm$timezone == "pdt") ~ "America/Los_Angeles",
         (cgm$timezone == "mst" | cgm$timezone == "mdt") ~ "America/Denver",
         (cgm$timezone == "cst" | cgm$timezone == "cdt") ~ "America/Chicago", 
         (cgm$timezone == "est" | cgm$timezone == "edt") ~ "America/New_York"))
```

# Convert to local time

```{r}
#| message: false
#| warning: false
cgm <- cgm |>
  rowwise() |>
  mutate(dt_local = 
           with_tz(effective_time_frame.time_interval.start_date_time, location)) |>
  ungroup()
```

# Remove duplicates

```{r}
#| message: false
#| warning: false
cgm <- cgm |>
  distinct()
```

# Get unusual cgms and remove from dataset

```{r}
#| message: false
#| warning: false
cgm <- cgm |>
  mutate(is_unusual = (blood_glucose.value > 400 | blood_glucose.value < 40) | is.na(blood_glucose.value))
normal_cgm <- cgm |>
  filter(is_unusual == FALSE)
```

# Create reading-level table

```{R}
#| message: false
#| warning: false
reading_cgm <- normal_cgm |> 
  select(blood_glucose.value, dt_local)
head(reading_cgm)
```

# Count days

```{R}
#| message: false
#| warning: false
daycounts <- normal_cgm |> 
  group_by(uuid) |>
  count(date(dt_local))
head(daycounts)
```

# Remove invalid days

```{R}
#| message: false
#| warning: false
normal_cgm_readings <- normal_cgm |> 
  mutate("date(dt_local)" = date(dt_local)) |>
  left_join(daycounts, by = "date(dt_local)" ) |>
  filter(n >= 202) |>
  select(!n) |>
  select(!`date(dt_local)`)
```

# Create summary table

```{R}
#| message: false
#| warning: false
validdaycounts <- filter(daycounts, n >= 202)
summary <- list(num_readings = nrow(normal_cgm), 
                num_days = nrow(validdaycounts), 
                mean_cgm = mean(normal_cgm$blood_glucose.value, na.rm = TRUE),
                median_cgm = median(normal_cgm$blood_glucose.value, na.rm = TRUE),
                sd_cgm = sd(normal_cgm$blood_glucose.value, na.rm = TRUE),
                CV_cgm = (sd(normal_cgm$blood_glucose.value, na.rm = TRUE)/
                            mean(normal_cgm$blood_glucose.value, na.rm = TRUE)) * 100,
                medium_cgm = sum((
                  normal_cgm$blood_glucose.value > 70 & 
                    normal_cgm$blood_glucose.value < 180), na.rm = TRUE) * 100/
                  nrow(normal_cgm),
                low_cgm = sum((normal_cgm$blood_glucose.value < 70), na.rm = TRUE) * 100/
                  nrow(normal_cgm),
                high_cgm = sum((normal_cgm$blood_glucose.value > 180), na.rm = TRUE) * 100/
                  nrow(normal_cgm))

summary

```

# Participant day data

```{R}
#| message: false
#| warning: false
day_time_start <- "06:00:00"
day_time_end <- "23:59:59"
normal_cgm <- normal_cgm |>
  mutate(day = date(dt_local)) |>
  ungroup() |>
  group_by(uuid, day) |>
  add_count(day) |>
  rename(num_readings_day = n) |>
  mutate(daily_pct_expected = num_readings_day * 100 / 288) |>
  mutate(daily_avg_cgm = mean(blood_glucose.value)) |>
  mutate(daily_cgm_sd = sd(blood_glucose.value)) |>
  mutate(cgm_level = case_when(blood_glucose.value > 70 & 
                    blood_glucose.value < 180 ~ "mid", 
                   blood_glucose.value < 70 ~ "low",
                   blood_glucose.value > 180 ~ "high")) |>
  ungroup() |>
  group_by(uuid, day, cgm_level) |>
  add_count(cgm_level) |>
  rename(num_category = n) |>
  mutate(pct_category = num_category * 100 / 288) |>
  ungroup() |>
  group_by(uuid, day) |>
  mutate(time_local = format(dt_local, format = "%H:%M:%S")) |>
  mutate(is_day = case_when(as.ITime(time_local) >= as.ITime(day_time_start) & 
                              as.ITime(time_local) <= as.ITime(day_time_end) ~ TRUE, 
                            as.ITime(time_local) < as.ITime(day_time_start) | 
                              as.ITime(time_local) > as.ITime(day_time_end) ~ FALSE)) |>
  add_count(is_day) |>
  ungroup() |>
  group_by(uuid, day, is_day) |>
  mutate(day_night_avg = mean(blood_glucose.value)) |>
  mutate(day_night_sd = sd(blood_glucose.value)) |>
  ungroup() |>
  group_by(uuid)
glimpse(normal_cgm)
```

# Tables and Figures

```{r}
#| message: false
#| warning: false
tibble(
  ParticipantID = 1042,
  NormalCGMCount = normal_cgm |> 
    filter(uuid == "AIREADI-1042") |> 
    nrow(),
  UnusualCGMCount = cgm |>
    filter(is_unusual == TRUE & uuid == "AIREADI-1042") |>
    nrow(),
  NormalDayCount = daycounts |> 
    filter(n >= 202 & uuid == "AIREADI-1042") |> 
    nrow(),
  NonNormalDayCount = daycounts |>
    filter(n < 202 & uuid == "AIREADI-1042") |>
    nrow()
) |>
gt()

ggplot(data = cgm |> 
         filter(uuid == "AIREADI-1042"), 
       mapping = aes(x = dt_local, y = blood_glucose.value)) +
  geom_line() + 
  geom_vline(data = subset(cgm |> 
                             filter(uuid == "AIREADI-1042"), is.na(blood_glucose.value)), 
             aes(xintercept = dt_local), color = "red", linetype = "dashed")

ggplot(data = normal_cgm |> filter(uuid == "AIREADI-1042"), 
       mapping = aes(x = dt_local, y = blood_glucose.value)) +
  geom_line()

cgm |>
  filter(date(dt_local) == ymd("2023-10-13")) |>
  ggplot(mapping = aes(x = dt_local, y = blood_glucose.value)) +
  geom_line() + 
  geom_vline(data = subset(cgm |>
  filter(date(dt_local) == ymd("2023-10-13")), is.na(blood_glucose.value)), 
             aes(xintercept = dt_local), color = "red", linetype = "dashed")

normal_cgm |>
  filter(uuid == "AIREADI-1042") |>
  mutate(time = dt_local) |>
  mutate(gl = blood_glucose.value) |>
  mutate(id = 1042) |>
  plot_agp(LLTR = 40)
```
