library(nycflights13)
library(tidyverse)
View(flights)
lateflights <- flights |> filter(arr_delay >= 120) 
houflights <- flights |> filter(dest == "IAH" | dest == "HOU")
uadlaaflights <- flights |> filter(carrier == "UA" | carrier == "DL" | carrier == "AA")
summerflights <- flights |> filter(month == 7 | month == 8 | month == 9)
slowflights <- flights |> filter(dep_time == sched_dep_time & arr_time == sched_arr_time)
fastflights <- flights |> filter(dep_delay >= 60 & dep_delay - arr_delay >= 30)
flightsbydelay <- flights |> arrange(desc(dep_delay))
flightsbyearlyness <- flights |> arrange(dep_time)
flightsbyspeed <- flights |> arrange(distance / air_time)
numdayswithflights <- flights |> distinct(month, day) |> nrow()
